version: "3.9"

services:
  web:
    build:
      context: "Web"
    image: "localhost:7002/weather-web:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
    environment:
      - API_URL=${API_URL}
    command: echo "${API_URL}" > /usr/share/nginx/html/config/api-url
  api:
    build:
      context: "API"
    image: "localhost:7002/weather-api:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
    depends_on:
      - "db"
    environment:
      - DB_CONNECTION_STRING=Server=${DB_CONT_NAME},1433;Initial Catalog=WeatherForecast;User ID=sa;Password=yourStrongP@ssword;MultipleActiveResultSets=True;
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "${DB_CONT_NAME}"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongP@ssword
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - weatherData:/var/opt/mssql:rw

volumes:
  weatherData: